services:
  web:
    image: nginx:alpine
    container_name: terra-aventura-web
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - npm_net

  php:
    build: ./php
    container_name: terra-aventura-php
    volumes:
      - ./:/var/www/html
    networks:
      - npm_net

  db:
    image: mariadb:10.11
    container_name: terra-aventura-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: terra_aventura
      MYSQL_USER: terra
      MYSQL_PASSWORD: terra
    volumes:
      - terra-aventura-db-data:/var/lib/mysql
    networks:
      - npm_net

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: terra-aventura-pma
    environment:
      PMA_HOST: terra-aventura-db
      PMA_USER: suprem
      PMA_PASSWORD: MOT_DE_PASSE_SUPREM
    networks:
      - npm_net

volumes:
  terra-aventura-db-data:

networks:
  npm_net:
    external: true
    name: npm-net
